server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/product/**
        - id: ecomarket
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/ecomarket/**

eureka:
  client: 
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
